spring:
  config:
    import:
      - classpath:/application-jwt-secret.yml
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:mysql://127.0.0.1:3310/assignment
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        show_sql: true
logging:
  level:
    root: INFO

server:
  port: 8080

